/* ============================================================================
 * data-model.data.js — NGUỒN DỮ LIỆU DUY NHẤT cho sơ đồ data-model (biên tập tay).
 * web/data-model.html nạp file này; tools/data-model/gen-data-model.mjs đọc nó để:
 *   - sinh phần schema (mermaid) trong docs/data-model.md, và
 *   - đối chiếu với schema.json (dump từ EF AppDbContext.Model) -> báo bảng/cột lệch DB.
 * Sửa schema ở ĐÂY (+ code/EF), rồi chạy generator. ĐỪNG sửa mảng trong .html (đã chuyển ra đây).
 * GROUPS = nhóm + màu; T = bảng + cột [name,type,note,flag]; INFO = giải thích/ví dụ/vòng đời.
 * ========================================================================== */
const GROUPS = {
  core:   {name:"Nền tảng & SaaS",        color:"#6c8cff", desc:"Văn phòng/công ty, multi-tenant"},
  invoice:{name:"Hóa đơn điện tử",        color:"#46c1a6", desc:"Đồng bộ HĐ từ cổng thuế"},
  gl:     {name:"GL — Lõi kế toán",       color:"#ffb454", desc:"Chứng từ & bút toán Nợ/Có (trái tim hệ thống)"},
  master: {name:"Danh mục (master-data)", color:"#c084fc", desc:"Đối tượng, vật tư, TK, danh mục dùng chung"},
  cash:   {name:"Tiền mặt / Quỹ",         color:"#34d399", desc:"Thu/chi, kiểm kê quỹ, dòng tiền"},
  asset:  {name:"CCDC & TSCĐ",            color:"#f472b6", desc:"Phân bổ công cụ & khấu hao tài sản"},
  payroll:{name:"Tiền lương",             color:"#fb923c", desc:"Bảng lương, BHXH, TNCN"},
  tax:    {name:"Thuế",                   color:"#f87171", desc:"Tờ khai GTGT liên kỳ"},
  stock:  {name:"Kho (tồn kho)",          color:"#38bdf8", desc:"Nhập/xuất/tồn, kiểm kê, chuyển kho"},
  costing:{name:"Giá thành",              color:"#a3e635", desc:"Tập hợp chi phí (THCP) & tính Z"},
  sales:  {name:"Bán hàng",               color:"#22d3ee", desc:"Báo giá, đơn hàng, giá, DT nhận trước"},
  opening:{name:"Số dư đầu kỳ chi tiết",  color:"#facc15", desc:"Công nợ/tồn kho/TK ngân hàng đầu kỳ"},
  setup:  {name:"Thiết lập & Auth",       color:"#94a3c4", desc:"Tùy chọn, người dùng, nhật ký"},
  hkd:    {name:"Hộ kinh doanh (TT152)",  color:"#fb7185", desc:"Doanh thu HKD, sổ theo bậc thuế (không GL)"},
};

/* ============ DATA: tables ============
  field: [name, type, note, flag]  flag: "pk" | tableId(fk) | "" */
const T = [
/* ---------- core ---------- */
{id:"tenant",g:"core",t:"tenants",f:"Văn phòng (chủ SaaS)",
 d:"Đơn vị thuê bao cao nhất. Hiện dùng 1 tenant mặc định; để sẵn cho SaaS sau này.",
 fields:[["Id","uuid","",  "pk"],["Name","string","tên văn phòng"]]},
{id:"company",g:"core",t:"companies",f:"Công ty (khách hàng dịch vụ)",
 d:"Mỗi công ty kế toán là 1 dòng. MST = username cổng thuế. Mật khẩu cổng thuế mã hóa AES-GCM.",
 fields:[["Id","uuid","","pk"],["TenantId","uuid","seam multi-tenant","tenant"],
  ["TaxCode","string","MST = username cổng thuế"],["Name","string"],
  ["InvoiceSourceKey","string","Gdt | Tvan | Misa"],
  ["EncryptedTaxPortalPassword","string","AES-GCM, không plaintext"],
  ["+ thông tin DN","…","Logo, Địa chỉ, Tỉnh/Huyện, Lĩnh vực, ngành nghề, TK NH mặc định"],
  ["Circular","int","TT99 (DN) / TT152 (HKD) …"],
  ["Unit","int","DN | Hộ kinh doanh"],
  ["+ cấu hình HKD","int?/string?","BookkeepingForm, HkdRevenueGroup, HkdVatMethod, HkdPitMethod, ngành/nguồn DT ngầm định (TT152)"],
  ["CostingMethod","int","PP tính giá xuất kho: bình quân / FIFO"],
  ["AllowNegativeStock","bool","cho phép xuất kho khi âm (mặc định false = chặn bán quá tồn)"],
  ["IsActive","bool"]]},

/* ---------- invoice ---------- */
{id:"invoice",g:"invoice",t:"invoices",f:"Hóa đơn (đầu vào/ra)",
 d:"Hóa đơn tải về từ cổng thuế. UNIQUE (Company, Direction, SourceInvoiceId) ⇒ quét lại không trùng.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Direction","int","1=mua vào · 2=bán ra"],
  ["SourceInvoiceId","string","id TCT — chống trùng (idempotent)"],
  ["SellerTaxCode / SellerName","string","bên bán"],
  ["BuyerTaxCode / BuyerName","string","bên mua"],
  ["Serial / Number","string","ký hiệu + số HĐ"],
  ["IssuedAt","datetime","ngày phát hành"],
  ["AmountBeforeTax / VatAmount / TotalAmount","decimal","tiền trước thuế / VAT / tổng"],
  ["ProcessingStatus","int","trạng thái xử lý TCT"],["SyncedAt","datetime"]]},
{id:"invoice_line",g:"invoice",t:"invoice_lines",f:"Dòng hàng của hóa đơn",
 d:"Chi tiết từng mặt hàng trên một hóa đơn.",
 fields:[["Id","uuid","","pk"],["InvoiceId","uuid","","invoice"],
  ["ItemName / Unit / Quantity / UnitPrice","…","mặt hàng, ĐVT, SL, đơn giá"],
  ["Amount / VatRate / VatAmount","…","thành tiền & thuế suất"]]},
{id:"sync_run",g:"invoice",t:"sync_runs",f:"Nhật ký lần đồng bộ",
 d:"Mỗi lần worker chạy đồng bộ HĐ ghi 1 dòng log (chạy / thành công / lỗi).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["StartedAt / FinishedAt","datetime"],
  ["Status","int","0=Running · 1=Succeeded · 2=Failed"],
  ["InvoicesFetched","int","số HĐ lấy về"],["Error","string"]]},

/* ---------- gl ---------- */
{id:"account",g:"gl",t:"accounts",f:"Hệ thống tài khoản (chart)",
 d:"Cây tài khoản chuẩn MISA (206 TK). Chỉ TK lá (IsPostable) mới được ghi sổ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code","string","111, 1111, 6428…"],["Name","string"],
  ["ParentCode","string","cây tài khoản"],["Circular","string","TT133 | TT200"],
  ["Kind","int","Asset/Liability/Equity/Revenue/Expense"],
  ["NormalSide","int","Debit | Credit"],
  ["IsPostable","bool","TK lá mới được ghi (= !is_parent)"],
  ["TrackByPartner","bool","131/331 → bắt buộc có đối tượng"],
  ["TrackByBankAccount","bool","112 → theo dõi theo TK ngân hàng"],
  ["TrackByContract","bool","theo dõi theo hợp đồng"]]},
{id:"fiscal_period",g:"gl",t:"fiscal_periods",f:"Kỳ kế toán",
 d:"Kỳ tháng/năm. Kỳ Closed thì không cho tạo/sửa chứng từ (khóa kỳ).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Year","int"],["Month","int","null nếu kỳ năm"],
  ["Status","int","Open | Closed"]]},
{id:"opening_balance",g:"gl",t:"opening_balances",f:"Số dư đầu kỳ (cấp TK)",
 d:"Dư Nợ/Có đầu năm của mỗi TK. Các tab chi tiết (công nợ/tồn kho) roll-up về đây.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["AccountCode","string","","account"],["Year","int"],
  ["OpeningDebit / OpeningCredit","decimal","dư Nợ / dư Có đầu kỳ"]]},
{id:"voucher",g:"gl",t:"vouchers",f:"Chứng từ ⭐",
 d:"Đơn vị ghi sổ. Posted ⇒ Σ Nợ = Σ Có. Đánh số theo kỳ (PT/PC/BC/UNC/BH/KC/PKT…). Xóa mềm (thùng rác).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Type","int","OtherEntry/FromInvoice/Cash·Bank Receipt·Payment/Sales/Purchase…"],
  ["Number","string","số CT theo kỳ"],
  ["Date / DocumentDate / CashBookDate","date","ngày HT / ngày CT / ngày ghi sổ quỹ"],
  ["Status","int","Draft | Posted"],
  ["SourceInvoiceId","string","null nếu nhập tay (chống trùng auto-HT)"],
  ["SourceVoucherId","uuid?","CT điều chỉnh → trỏ CT gốc","voucher"],
  ["ObjectCode/Name/Address","string","đối tượng header (KH/NCC/NV)"],
  ["RecipientName / EmployeeCode","string","người nộp·nhận tiền / NV tạm ứng"],
  ["Reason / AttachedDocs / KindId","…","lý do thu·chi, kèm theo, loại con"],
  ["InvoiceNo / InvoiceDate","string?/date?","số+ngày HĐ GTGT thật khai trên phiếu"],
  ["IsDeleted / DeletedAt / DeletedBy","…","xóa mềm — thùng rác"],
  ["CreatedBy/At · UpdatedBy/At","…","audit: người/ngày tạo·sửa"]]},
{id:"journal_line",g:"gl",t:"journal_lines",f:"Dòng bút toán ⚖️",
 d:"Một dòng Nợ hoặc Có vào 1 TK lá. Tổng Nợ = tổng Có trong cùng voucher. Gắn nhiều chiều phân tích.",
 fields:[["Id","uuid","","pk"],["VoucherId","uuid","","voucher"],
  ["AccountCode","string","phải là TK lá IsPostable","account"],
  ["Debit / Credit","decimal","số tiền Nợ / Có"],["Description","string"],
  ["PartnerTaxCode","string","đối tượng công nợ"],
  ["CostItem / CashFlowItem","string","khoản mục CP / mục thu-chi"],
  ["ContractCode / CostObjectCode","string?","HĐ / đối tượng THCP (giá thành)"],
  ["DepartmentCode","string?","bộ phận — phân bổ CP/KH theo bộ phận","department"],
  ["BankAccount","string","bắt buộc khi TK theo dõi NH (112)"]]},
{id:"invoice_payment",g:"gl",t:"invoice_payments",f:"Phân bổ thanh toán / đối trừ",
 d:"Khớp phiếu thu/chi (hoặc chứng từ ghi 131) với hóa đơn còn nợ. Đối trừ 131 không sinh bút toán.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["InvoiceId","uuid","HĐ được khớp","invoice"],
  ["VoucherId","uuid","phiếu thu·chi khớp","voucher"],
  ["Amount","decimal","số tiền phân bổ cho HĐ này"],["Date","date"]]},
{id:"transfer_account_pair",g:"gl",t:"transfer_account_pairs",f:"Cặp tài khoản kết chuyển",
 d:"Danh mục cặp TK kết chuyển cuối kỳ (engine thực tế chạy theo AccountKind).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Order","…","mã + thứ tự"],["FromAccount → ToAccount","string","kết chuyển từ → đến"],
  ["Side","int","Debit/Credit/Both"],["Description","string?","loại kết chuyển"]]},
{id:"posting_rule",g:"gl",t:"posting_rules",f:"Quy tắc hạch toán",
 d:"Khung quy tắc auto-hạch toán (Loại phiếu → TK Nợ/Có thực ra đọc từ JSON embed, không lưu DB).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"]]},
{id:"default_account",g:"gl",t:"default_accounts",f:"Tài khoản ngầm định",
 d:"Ánh xạ nghiệp vụ → TK mặc định (tiền mặt=111, phải thu=131…). UNIQUE (Company, Purpose).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Purpose","string","mã nghiệp vụ"],["Name","string","tên hiển thị"],
  ["Account","string?","TK ngầm định","account"],["Description","string?"]]},

/* ---------- master ---------- */
{id:"partner",g:"master",t:"partners",f:"Đối tượng (KH / NCC / NV)",
 d:"Khách hàng, nhà cung cấp, nhân viên, khác. TK công nợ ngầm định 131/331.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code","string","KH/NCC/NV#####"],["Name","string"],
  ["Kind","int","Customer/Supplier/Employee/Other"],
  ["IsOrganization","bool","Tổ chức / Cá nhân"],["TaxCode","string","MST hoặc CCCD"],
  ["Address/Phone/Website","…"],["GroupName","string","→ danh mục partner_groups","partner_group"],
  ["ContactPerson/Email/Phone","…","người liên hệ"],
  ["ReceivableAccount / PayableAccount","string","TK công nợ 131 / 331","account"],
  ["PaymentTermDays / MaxDebt / CreditLimit","…","hạn nợ & hạn mức"],
  ["DepartmentCode/Title/IdNumber","…?","riêng NV (phòng ban/chức danh/CCCD)"],
  ["Note / IsActive","…"]]},
{id:"partner_bank_account",g:"master",t:"partner_bank_accounts",f:"TK ngân hàng của đối tượng",
 d:"Một đối tượng có nhiều số TK ngân hàng.",
 fields:[["Id","uuid","","pk"],["PartnerId","uuid","","partner"],
  ["AccountNumber / BankName / Branch / Province","…","số TK, NH, chi nhánh, tỉnh"]]},
{id:"item",g:"master",t:"items",f:"Vật tư / hàng hóa / dịch vụ",
 d:"IsService = nguồn sự thật định tuyến kho. Kind = metadata 5 loại MISA (đồng bộ với IsService).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Name / Unit","…","Unit → danh mục units","unit"],
  ["IsService","bool","quyết định có quản kho không"],
  ["Kind","int","HangHoa·ThanhPham·DichVu·NVL·CCDC"],
  ["GroupCode","string?","→ item_groups","item_group"],
  ["InventoryAccount / CogsAccount / ReturnAccount","string?","TK kho 152·156 / giá vốn 632 / hàng trả 5212","account"],
  ["RevenueAccount / ExpenseAccount","string","TK doanh thu / chi phí","account"],
  ["VatRate / IsActive","…"]]},
{id:"cost_item",g:"master",t:"cost_items",f:"Khoản mục chi phí (KMCP)",
 d:"Phân loại chi phí theo cây (ParentCode). Gắn vào dòng bút toán để báo cáo chi phí.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Name","…"],["ParentCode","string?","KMCP cha (cây)"],["Description","string?"]]},
{id:"bank_account",g:"master",t:"bank_accounts",f:"Tài khoản ngân hàng (của công ty)",
 d:"Số TK ngân hàng của chính công ty. GlAccount = TK sổ cái (mặc định 112).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["AccountNumber / BankName / Branch","…"],["AccountHolder","string?","chủ tài khoản"],
  ["GlAccount","string","TK sổ cái (112)","account"],["IsActive","bool"]]},
{id:"unit",g:"master",t:"units",f:"Đơn vị tính (ĐVT)",d:"Danh mục ĐVT dùng chung.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"]]},
{id:"item_group",g:"master",t:"item_groups",f:"Nhóm vật tư hàng hóa",d:"Cây nhóm VTHH (ParentCode).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],["ParentCode","string?"]]},
{id:"partner_group",g:"master",t:"partner_groups",f:"Nhóm KH / NCC",d:"Danh mục nhóm đối tượng.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"]]},
{id:"tool_type",g:"master",t:"tool_types",f:"Loại CCDC",d:"Phân loại công cụ dụng cụ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name / Description","…"]]},
{id:"fixed_asset_type",g:"master",t:"fixed_asset_types",f:"Loại tài sản cố định",
 d:"Phân loại TSCĐ + TK nguyên giá/khấu hao/chi phí mặc định.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["AssetAccount / DepreciationAccount / ExpenseAccount","string?","","account"]]},
{id:"project_type",g:"master",t:"project_types",f:"Loại công trình",d:"Danh mục loại công trình.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"]]},
{id:"bank",g:"master",t:"banks",f:"Ngân hàng",d:"Danh mục ngân hàng.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name / ShortName","…"]]},
{id:"payment_term",g:"master",t:"payment_terms",f:"Điều khoản thanh toán",
 d:"Số ngày được nợ + chiết khấu thanh toán sớm.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["Days","int","số ngày được nợ"],["DiscountPercent / DiscountDays","…?","CK% / thời hạn hưởng CK"]]},
{id:"statistical_code",g:"master",t:"statistical_codes",f:"Mã thống kê",d:"Mã thống kê tự do.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name / Description","…"]]},
{id:"voucher_kind",g:"master",t:"voucher_kinds",f:"Loại chứng từ (theo TK)",
 d:"Mã loại nghiệp vụ + TK Nợ/Có gợi ý — lọc 'Lý do thu/chi'.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["DebitAccount / CreditAccount","string?","TK Nợ / Có","account"],["Description","string?"]]},
{id:"department",g:"master",t:"departments",f:"Phòng ban / bộ phận",d:"Chiều phân bổ lương.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"]]},
{id:"employee",g:"master",t:"employees",f:"Nhân viên (cho bảng lương)",
 d:"Prefill Tên/Mã/Lương cơ bản/Số NPT khi lập bảng lương.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["DepartmentCode","string?","→ departments","department"],["Position","string?"],
  ["BaseSalary / Dependents","…","lương cơ bản / số NPT"],["TaxCode","string?","MST cá nhân (TNCN)"]]},
{id:"contract",g:"master",t:"contracts",f:"Hợp đồng (sổ đăng ký)",
 d:"Sổ đăng ký HĐ bán/mua. Gắn vào dòng bút toán qua ContractCode để báo cáo lãi/lỗ theo HĐ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number","string"],["Kind","int","Sales / Purchase"],["PartnerName","string?"],
  ["SignedDate / Value","…","ngày ký / giá trị"],["Description","string?"],["Closed","bool"]]},

/* ---------- cash ---------- */
{id:"cash_flow_item",g:"cash",t:"cash_flow_items",f:"Mục thu / chi (dòng tiền)",
 d:"Phân loại dòng tiền cho báo cáo Lưu chuyển & Dự báo. Gắn vào dòng bút toán (CashFlowItem).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["Direction","int","1=Thu · 2=Chi · 3=Cả hai"],["IsRecurring / IsActive","…"]]},
{id:"cash_count",g:"cash",t:"cash_counts",f:"Bảng kiểm kê quỹ",
 d:"Đối chiếu tồn quỹ sổ vs thực tế. Chênh lệch → sinh phiếu thu/chi xử lý (idempotent).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date / AccountCode","…","","account"],
  ["BookBalance / ActualBalance","decimal","theo sổ / thực tế (Difference = computed)"],
  ["Purpose / Conclusion","…"],["IsProcessed","bool"],
  ["ProcessVoucherId","uuid?","phiếu xử lý chênh lệch","voucher"]]},
{id:"cash_count_denom",g:"cash",t:"cash_count_denominations",f:"Mệnh giá kiểm kê (owned)",
 d:"Mệnh giá × số lượng tờ của 1 bảng kiểm kê quỹ.",
 fields:[["CashCountId","uuid","","cash_count"],["Denomination / Quantity","…"]]},
{id:"cash_count_member",g:"cash",t:"cash_count_members",f:"Thành viên kiểm kê quỹ (owned)",
 d:"Hội đồng kiểm kê của 1 bảng kiểm kê.",
 fields:[["CashCountId","uuid","","cash_count"],["Name / Title","…"]]},
{id:"bank_reconciliation",g:"cash",t:"bank_reconciliations",f:"Đối chiếu ngân hàng",
 d:"So khớp sao kê NH với sổ. Lưu danh sách voucher đã khớp.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["BankAccount / FromDate / ToDate","…"],["StatementBalance","decimal","số dư sao kê"],
  ["MatchedVoucherIds","string","voucher đã khớp"],["Confirmed","bool"]]},
{id:"loan_contract",g:"cash",t:"loan_contracts",f:"Khế ước đi vay (+ lịch)",
 d:"Hợp đồng vay + lịch trả gốc/lãi (module Tiền gửi). Lịch tính trực tiếp.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["… (số tiền, lãi suất, kỳ hạn, lịch trả gốc/lãi)","…"]]},

/* ---------- asset ---------- */
{id:"tool",g:"asset",t:"tools",f:"CCDC (công cụ dụng cụ)",
 d:"Phân bổ dần vào chi phí. Phân bổ kỳ: Nợ 627/641/642 / Có 242 (idempotent). IsOpening = đầu kỳ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Name / Quantity","…"],["OriginalValue","decimal","nguyên giá"],
  ["IncrementDate / AllocationStart","date","ngày ghi tăng / bắt đầu phân bổ"],
  ["AllocationMonths","int","số kỳ phân bổ"],
  ["ExpenseAccount / AssetAccount","string","TK CP 627·641·642 / TK 242","account"],
  ["CostItem / Note / Closed","…"],
  ["IsOpening / OpeningAllocated","…","đầu kỳ + đã phân bổ lũy kế đầu kỳ"],
  ["DepartmentCode / ToolTypeCode","string","đơn vị sử dụng (soft FK departments) / loại CCDC (tool_types)"]]},
{id:"tool_allocation",g:"asset",t:"tool_allocations",f:"Kỳ đã phân bổ CCDC (owned)",
 d:"Log mỗi kỳ đã phân bổ — dùng để idempotent.",
 fields:[["ToolId","uuid","","tool"],["Year / Month / Amount","…"],
  ["VoucherId","uuid","voucher phân bổ kỳ","voucher"]]},
{id:"tool_alloc_target",g:"asset",t:"tool_allocation_targets",f:"Thiết lập phân bổ CCDC (owned)",
 d:"Phân bổ CP CCDC về nhiều đối tượng/bộ phận theo % (MISA Form 3). Rỗng → 1 dòng theo ExpenseAccount mặc định.",
 fields:[["ToolId","uuid","","tool"],["DepartmentCode","string?","đối tượng/bộ phận — soft FK departments"],
  ["ExpenseAccount","string","TK CP lá 627·641·642","account"],["CostItem","string?","khoản mục CP"],
  ["Percent","decimal","tỷ lệ % (Σ≈100)"]]},
{id:"tool_count",g:"asset",t:"tool_counts",f:"Kiểm kê CCDC",
 d:"Đối chiếu CCDC theo sổ ↔ thực tế. Thiếu/mất: Nợ 1381 (GTCL) / Có 242 + đóng sổ. Thừa: Nợ 242 / Có 3381.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date","…","số + ngày kiểm kê"],["Purpose / Conclusion","…"],
  ["IsProcessed / ProcessVoucherId","…","đã xử lý + chứng từ"],
  ["Lines (owned)","tool_count_lines","ToolId, ToolCode, AssetAccount, BookRemaining, Exists, IsSurplus, Note, SurplusAllocationMonths, SurplusExpenseAccount (ghi tăng CCDC thừa vào sổ)"]]},
{id:"fixed_asset",g:"asset",t:"fixed_assets",f:"Tài sản cố định (TSCĐ)",
 d:"Khấu hao dần. Khấu hao kỳ: Nợ 627/641/642 / Có 214 (hao mòn lũy kế). Giá trị còn lại = NG − Σ hao mòn.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Name / Quantity","…"],["OriginalValue","decimal","nguyên giá"],
  ["PurchaseDate / DepreciationStart","date"],["DepreciationMonths","int"],
  ["CostAccount / DepreciationAccount / ExpenseAccount","string","211·213 / 214 / 627·641·642","account"],
  ["CostItem / Note / Closed","…"],
  ["IsOpening / OpeningAccumulated","…","đầu kỳ + hao mòn lũy kế đầu kỳ"],
  ["DepartmentCode","string","bộ phận sử dụng — soft FK departments (điều chuyển/báo cáo)"],
  ["AssetTypeCode","string","loại tài sản — soft FK fixed_asset_types"]]},
{id:"fixed_asset_count",g:"asset",t:"fixed_asset_counts",f:"Kiểm kê TSCĐ",
 d:"Đối chiếu TSCĐ theo sổ ↔ thực tế. TSCĐ thiếu/mất: Nợ 1381(GTCL)+Nợ 214(HM)/Có 211(NG) + đóng sổ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date","…","số + ngày kiểm kê"],["Purpose / Conclusion","…","mục đích/kết luận"],
  ["IsProcessed / ProcessVoucherId","…","đã xử lý + chứng từ"],
  ["Lines (owned)","fixed_asset_count_lines","AssetId, AssetCode, BookOriginalValue, BookAccumulated, Exists, IsSurplus, Note, SurplusDepreciationMonths, SurplusExpenseAccount (ghi tăng TSCĐ thừa vào sổ)"]]},
{id:"fixed_asset_dep",g:"asset",t:"fixed_asset_depreciations",f:"Kỳ đã khấu hao (owned)",
 d:"Log mỗi kỳ đã khấu hao — idempotent.",
 fields:[["FixedAssetId","uuid","","fixed_asset"],["Year / Month / Amount","…"],
  ["VoucherId","uuid","","voucher"]]},
{id:"asset_transfer",g:"asset",t:"asset_transfers",f:"Biên bản giao nhận (điều chuyển hàng loạt)",
 d:"Điều chuyển TSCĐ/CCDC hàng loạt giữa bộ phận. KHÔNG sinh GL — chỉ đổi DepartmentCode + lưu biên bản. In QuestPDF.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Kind","enum","FixedAsset / Tool"],["Number / Date","…","số ĐCTS·ĐCCC + ngày"],
  ["ToDepartment","string?","đến bộ phận/đơn vị"],["Deliverer / Receiver","string?","người bàn giao / tiếp nhận"],
  ["Reason","string?","lý do điều chuyển"],
  ["Lines (owned)","asset_transfer_lines","AssetId, AssetCode, AssetName, FromDepartment"]]},

/* ---------- payroll ---------- */
{id:"payroll_sheet",g:"payroll",t:"payroll_sheets",f:"Bảng lương (1 kỳ)",
 d:"Hạch toán: Nợ 642/641/622 / Có 334 + trích BH + TNCN. TNCN lũy tiến 7 bậc.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Year / Month / Date","…"],
  ["ExpenseAccount","string","TK lá 642·641·622","account"],
  ["Posted","bool"],["VoucherId","uuid?","voucher hạch toán (idempotent)","voucher"]]},
{id:"payroll_line",g:"payroll",t:"payroll_lines",f:"Dòng nhân viên (owned)",
 d:"Lương theo công / income / BH / TNCN / thực lĩnh tính trong domain.",
 fields:[["PayrollSheetId","uuid","","payroll_sheet"],
  ["EmployeeName / EmployeeCode","…?"],["GrossSalary","decimal","mức đóng BH"],
  ["Dependents","int","số người phụ thuộc"],
  ["StandardDays / ActualDays","int","công chuẩn / thực"],
  ["Allowance","decimal","phụ cấp chịu thuế"]]},

/* ---------- tax ---------- */
{id:"tax_declaration",g:"tax",t:"tax_declarations",f:"Tờ khai GTGT (đã chốt)",
 d:"Tờ khai 01/GTGT 1 kỳ. Chỉ [22] là dữ liệu liên kỳ phải lưu; còn lại tính on-the-fly từ GL. UNIQUE (Company,Type,Kind,Year,Period).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Kind / Type","string","Tháng·Quý / 01/GTGT"],["Year / Period","int"],
  ["Ct22","decimal","GTGT chưa kh.trừ kỳ trước chuyển sang = [43] kỳ trước"],
  ["Ct23 / Ct25","decimal","HHDV mua vào / GTGT đầu vào được kh.trừ"],
  ["Ct34 / Ct35","decimal","DT bán ra / GTGT đầu ra"],
  ["Ct40a","decimal","còn phải nộp = max(0,[35]−([25]+[22]))"],
  ["Ct43","decimal","chưa kh.trừ hết chuyển kỳ sau"],["CreatedAt","datetime"]]},

/* ---------- stock ---------- */
{id:"warehouse",g:"stock",t:"warehouses",f:"Kho",d:"Danh mục kho per-company. UNIQUE (Company, Code).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Name","…"],["IsDefault / IsActive","…"]]},
{id:"stock_movement",g:"stock",t:"stock_movements",f:"Phát sinh kho (nhập/xuất) ⭐",
 d:"Tồn kho = view dẫn xuất từ đây. Giá vốn xuất = bình quân gia quyền di động.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date","…"],["Direction","int","1=Nhập · 2=Xuất"],
  ["ItemCode/Name/Unit","…","","item"],["Quantity / UnitCost / Value","decimal"],
  ["InventoryAccount / CounterAccount","string","152·153·155·156 / TK đối ứng","account"],
  ["WarehouseCode","string?","null = kho mặc định","warehouse"],
  ["VoucherId","uuid?","null nếu là số dư đầu kỳ","voucher"],["Note","string"]]},
{id:"stock_count",g:"stock",t:"stock_counts",f:"Bảng kiểm kê kho",
 d:"Kiểm kê tồn vật tư. Chênh lệch → sinh chứng từ xử lý (idempotent).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date / AsOfDate","…","đến ngày"],
  ["Purpose / WarehouseScope / Conclusion","…"],
  ["IsProcessed","bool"],["ProcessVoucherId","uuid?","","voucher"]]},
{id:"stock_count_line",g:"stock",t:"stock_count_lines",f:"Dòng kiểm kê kho (owned)",
 d:"DiffQty/DiffValue tính trong domain.",
 fields:[["StockCountId","uuid","","stock_count"],
  ["ItemCode/Name/Unit","…","","item"],["WarehouseCode","string","","warehouse"],
  ["InventoryAccount","string","","account"],
  ["BookQty / UnitCost / ActualQty","…","theo sổ / BQ / theo kiểm kê"],
  ["GoodQty / PoorQty / LostQty","…","tốt 100% / kém PC / mất PC"]]},
{id:"stock_count_member",g:"stock",t:"stock_count_members",f:"Thành viên kiểm kê kho (owned)",
 d:"Hội đồng kiểm kê.",
 fields:[["StockCountId","uuid","","stock_count"],["Name / Title","…"]]},

/* ---------- costing ---------- */
{id:"cost_object",g:"costing",t:"cost_objects",f:"Đối tượng tập hợp CP (THCP)",
 d:"Đối tượng tập hợp chi phí: SP / Công trình / Đơn hàng / HĐ bán. Công trình có thêm field dự án.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["Type","int","1=SP·2=Công trình·3=Đơn hàng·4=HĐ bán"],
  ["ProductCode / Unit / Note","…?","TP nhập kho"],["Inactive","bool"],
  ["ProjectType/Status/Start/End/Budget/Parent/Investor","…?","riêng Công trình","project_type"]]},
{id:"costing_period",g:"costing",t:"costing_periods",f:"Kỳ tính giá thành",
 d:"Lấy THCP có CP → phân bổ CP chung → Z = dở đầu + trực tiếp + phân bổ − dở cuối.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Name","…"],["FromDate / ToDate","date"],
  ["Approach","int","1 giản đơn·2 hệ số·3 tỷ lệ·4 công trình·5 đơn hàng·6 HĐ"],["Calculated","bool"]]},
{id:"costing_period_line",g:"costing",t:"costing_period_lines",f:"Dòng THCP trong kỳ (owned)",
 d:"Input + kết quả tính giá thành theo từng đối tượng.",
 fields:[["CostingPeriodId","uuid","","costing_period"],
  ["ObjectCode/Name/Type · ProductCode · Unit","…","","cost_object"],
  ["CompletedQty / OpeningWip / ClosingWip","…","SL hoàn thành / dở đầu / dở cuối"],
  ["DirectCost / AllocatedCost / TotalCost(Z) / UnitCost","decimal","snapshot kết quả"],
  ["ReceiptVoucherId","uuid?","phiếu nhập kho TP","voucher"]]},

/* ---------- sales ---------- */
{id:"price_policy",g:"sales",t:"price_policies",f:"Chính sách giá / bảng giá",
 d:"Khi lập chứng từ bán → tự lấy đơn giá hiệu lực.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Code / Name","…"],
  ["CustomerGroup / Description","…?"],["FromDate / ToDate / Inactive","…?"]]},
{id:"price_policy_line",g:"sales",t:"price_policy_lines",f:"Giá theo mặt hàng (owned)",
 fields:[["PricePolicyId","uuid","","price_policy"],
  ["ItemCode/Name/Unit","…","","item"],["UnitPrice","decimal"]]},
{id:"deferred_revenue",g:"sales",t:"deferred_revenues",f:"Doanh thu nhận trước",
 d:"Phân bổ dần: Nợ 3387 / Có 511. IsOpening = đầu kỳ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Code / Description","…"],["PartnerTaxCode","string?"],
  ["TotalAmount / StartDate / Months","…"],
  ["RevenueAccount / DeferredAccount","string","511x / 3387","account"],
  ["Closed","bool"],["IsOpening / OpeningAllocated","…"]]},
{id:"deferred_revenue_alloc",g:"sales",t:"deferred_revenue_allocations",f:"Kỳ đã phân bổ DT (owned)",
 d:"Idempotent theo kỳ.",
 fields:[["DeferredRevenueId","uuid","","deferred_revenue"],["Year / Month / Amount","…"],
  ["VoucherId","uuid","","voucher"]]},
{id:"sales_order",g:"sales",t:"sales_orders",f:"Đơn đặt hàng bán",
 d:"KHÔNG ghi sổ. 'Lập chứng từ bán hàng' → sinh doanh thu + giá vốn, đánh dấu Fulfilled.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date","…"],["PartnerTaxCode / Name","…"],["Description","string?"],
  ["Status","int","1 Mới·2 Đã lập CT·3 Hủy"],["VoucherId","uuid?","","voucher"]]},
{id:"sales_order_line",g:"sales",t:"sales_order_lines",f:"Dòng đơn hàng bán (owned)",
 fields:[["SalesOrderId","uuid","","sales_order"],
  ["ItemCode/Name","…?","","item"],["Account","string","511x","account"],
  ["Unit / Quantity / UnitPrice / VatRate","…"]]},
{id:"quotation",g:"sales",t:"quotations",f:"Báo giá",
 d:"KHÔNG ghi sổ. 'Chuyển thành đơn hàng' → dựng SalesOrder, đánh dấu Converted.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date","…"],["PartnerTaxCode / Name","…"],["Description","string?"],
  ["Status","int","1 Mới·2 Đã chuyển·3 Hủy"],["SalesOrderId","uuid?","","sales_order"]]},
{id:"quotation_line",g:"sales",t:"quotation_lines",f:"Dòng báo giá (owned)",
 fields:[["QuotationId","uuid","","quotation"],["… như sales_order_lines","…","","item"]]},
{id:"purchase_order",g:"sales",t:"purchase_orders",f:"Đơn đặt hàng mua",
 d:"KHÔNG ghi sổ. 'Lập chứng từ mua hàng' → sinh chứng từ mua, đánh dấu Fulfilled (như đơn bán nhưng chiều mua).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],
  ["Number / Date","…"],["PartnerTaxCode / Name","…","NCC"],["Description","string?"],
  ["Status","int","1 Mới·2 Đã lập CT·3 Hủy"],["VoucherId","uuid?","","voucher"]]},
{id:"purchase_order_line",g:"sales",t:"purchase_order_lines",f:"Dòng đơn mua (owned)",
 fields:[["PurchaseOrderId","uuid","","purchase_order"],
  ["ItemCode/Name","…?","","item"],["Account","string","152/156/6…","account"],
  ["Unit / Quantity / UnitPrice / VatRate","…"]]},

/* ---------- opening ---------- */
{id:"opening_party",g:"opening",t:"opening_parties",f:"Công nợ đầu kỳ (theo đối tượng)",
 d:"Dư công nợ đầu kỳ 131/331/141… theo từng đối tượng. Roll-up về opening_balances.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Year","int"],
  ["AccountCode","string","131/1388/331/3311/141…","account"],
  ["PartnerCode / PartnerName","…?","","partner"],
  ["Debit / Credit","decimal","dư Nợ / dư Có"]]},
{id:"opening_stock",g:"opening",t:"opening_stocks",f:"Tồn kho đầu kỳ (theo vật tư/kho)",
 d:"Khi lưu → sinh StockMovement Receipt (SDDK…) để view tồn kho đúng ngay, KHÔNG sinh bút toán GL.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Year","int"],
  ["ItemCode/Name/Unit","…?","","item"],["WarehouseCode","string?","","warehouse"],
  ["Quantity / UnitCost / Value","decimal","SL × đơn giá = giá trị"],
  ["InventoryAccount","string","152/156","account"]]},
{id:"opening_bank_balance",g:"opening",t:"opening_bank_balances",f:"Số dư TK ngân hàng đầu kỳ",
 d:"Dư đầu kỳ 112x theo từng số TK ngân hàng. Roll-up về opening_balances.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Year","int"],
  ["AccountCode","string","112x","account"],
  ["BankAccountNumber","string","từ danh mục bank_accounts","bank_account"],
  ["BankName","string?"],["Debit / Credit","decimal"]]},

/* ---------- setup ---------- */
{id:"company_settings",g:"setup",t:"company_settings",f:"Tùy chọn hệ thống",
 d:"1-1 với company. Không có bản ghi = dùng giá trị mặc định.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","UNIQUE","company"],
  ["FiscalYearStartMonth","int","tháng bắt đầu năm TC"],
  ["PostingDateMode","int","0=theo ngày CT · 1=nhập tay"],
  ["AmountDecimals / QuantityDecimals / UnitPriceDecimals","int","số chữ số thập phân"],
  ["NumberingRule","int","0=liên tục·1=theo tháng·2=theo năm"]]},
{id:"company_signature",g:"setup",t:"company_signatures",f:"Chữ ký (owned)",
 d:"Nhiều người ký trên chứng từ in.",
 fields:[["CompanyId","uuid","","company"],["Role / Title / Name","…","chức danh / tiêu đề / tên người ký"]]},
{id:"user",g:"setup",t:"users",f:"Người dùng (đăng nhập)",
 d:"PasswordHash PBKDF2. Role quyết định quyền hành động (RBAC).",
 fields:[["Id","uuid","","pk"],["TenantId","uuid","","tenant"],
  ["Email","string","đăng nhập, unique"],["FullName","string"],
  ["PasswordHash","string","PBKDF2 SHA256, 100k vòng"],
  ["Role","int","Admin/ChiefAccountant/Accountant/Viewer"],["IsActive","bool"]]},
{id:"audit_log",g:"setup",t:"audit_logs",f:"Nhật ký thao tác",
 d:"Ghi mọi Login/Create/Post/Update/Delete… Lọc theo EntityType+EntityId = 'nhật ký 1 phiếu'.",
 fields:[["Id","uuid","","pk"],["TenantId","uuid","","tenant"],
  ["CompanyId","uuid?","null = mức văn phòng (Login)","company"],
  ["UserId / UserName / Time","…"],
  ["Action","string","Login/Create/Post/Unpost/Update/Delete"],
  ["EntityType / EntityId","string","Voucher/…"],["Description","string"]]},
{id:"staff",g:"setup",t:"staff",f:"Nhân sự văn phòng",
 d:"Nhân viên của văn phòng dịch vụ (khác Partner=Employee của công ty khách).",
 fields:[["Id","uuid","","pk"],["TenantId","uuid","","tenant"],
  ["Name / Email / Phone / Title","…"]]},
{id:"company_assignment",g:"setup",t:"company_assignments",f:"Phân công phụ trách",
 d:"Nhân sự nào phụ trách công ty nào.",
 fields:[["Id","uuid","","pk"],["StaffId","uuid","","staff"],["CompanyId","uuid","","company"]]},

/* ---------- hkd (hộ kinh doanh) ---------- */
{id:"hkd_revenue",g:"hkd",t:"hkd_revenues",f:"Doanh thu hộ kinh doanh",
 d:"1 dòng doanh thu HKD (TT152, KHÔNG bút toán kép). Gắn nhóm ngành nghề → tỷ lệ % GTGT/TNCN. Sổ S1a/S2a + tính thuế dẫn xuất từ đây.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Date","date"],
  ["CareerGroupCode","string","mã ngành nghề tính thuế (danh mục TT18)"],
  ["Amount","decimal","doanh thu = cơ sở tính thuế %"],
  ["DocNo / Description","string?","số chứng từ / diễn giải"],
  ["InvoiceNo / InvoiceSerial / InvoiceDate","string?/date?","tham chiếu hóa đơn"]]},
{id:"hkd_expense",g:"hkd",t:"hkd_expenses",f:"Chi phí hộ kinh doanh (Bậc 3)",
 d:"1 dòng chi phí hợp lý HKD Bậc 3 (TT152 Sổ S2c, KHÔNG bút toán kép). Gắn 1 yếu tố (NVL/lương/khấu hao/dịch vụ mua ngoài/lãi vay/khác). Thu nhập tính thuế = doanh thu năm − Σ chi phí; thuế TNCN = thu nhập × 15/17/20% (Luật 109/2025 Điều 7).",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Date","date"],
  ["Factor","int","yếu tố chi phí (1=NVL · 2=lương · 3=khấu hao · 4=dịch vụ mua ngoài · 5=lãi vay · 6=khác)"],
  ["Amount","decimal","số tiền chi phí được trừ"],
  ["DocNo / Description","string?","số chứng từ / diễn giải"]]},
{id:"hkd_goods_line",g:"hkd",t:"hkd_goods_lines",f:"Sổ vật liệu/hàng hóa HKD (S2d)",
 d:"1 dòng nhập/xuất vật liệu, dụng cụ, SP, hàng hóa HKD Bậc 3 (TT152 Sổ S2d, KHÔNG bút toán kép). Dòng nhập có thành tiền; dòng xuất tính theo đơn giá bình quân gia quyền cả kỳ khi lập sổ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Date","date"],
  ["ItemName","string","tên vật liệu/hàng hóa (1 sổ/mặt hàng)"],["Unit","string?","đơn vị tính"],
  ["Direction","int","1=Nhập · 2=Xuất"],["Quantity","decimal","số lượng"],
  ["Amount","decimal","thành tiền (chỉ dòng nhập)"],["DocNo / Description","string?","số CT / diễn giải"]]},
{id:"hkd_cash_line",g:"hkd",t:"hkd_cash_lines",f:"Sổ chi tiết tiền HKD (S2e)",
 d:"1 dòng thu/chi tiền HKD Bậc 3 (TT152 Sổ S2e, KHÔNG bút toán kép). Phân theo loại tiền + chiều thu/chi; số dư lũy kế dẫn xuất khi lập sổ.",
 fields:[["Id","uuid","","pk"],["CompanyId","uuid","","company"],["Date","date"],
  ["Account","int","1=tiền mặt · 2=tiền gửi KKH · 3=tiền gửi CKH"],["BankName","string?","ngân hàng (tiền gửi)"],
  ["Direction","int","1=Thu/Gửi vào · 2=Chi/Rút ra"],["Amount","decimal","số tiền"],
  ["DocNo / Description","string?","số CT / diễn giải"]]},
];

/* ============ INFO: Feynman + ví dụ + vòng đời (thêm/sửa/xóa) ============ */
const INFO={
/* core */
tenant:{fey:"Giống 'công ty mẹ' chứa nhiều công ty con. Giờ chỉ có 1, để dành cho lúc bán cho nhiều văn phòng.",
 ex:"Văn phòng 'Lixin' chứa các công ty A, B, C.",
 add:"tạo văn phòng mới (hiện cố định 1)",upd:"đổi tên văn phòng",del:"gần như không xóa"},
company:{fey:"Mỗi khách hàng bạn nhận làm dịch vụ kế toán là 1 dòng. Như 1 ngăn tủ hồ sơ riêng cho từng công ty.",
 ex:"Công ty TNHH Cà Phê Sạch, MST 0312345678.",
 add:"nhận thêm 1 khách hàng dịch vụ",upd:"khách đổi địa chỉ / logo / mật khẩu cổng thuế",del:"ngừng làm → tắt IsActive (ít khi xóa hẳn)"},
/* invoice */
invoice:{fey:"Tờ hóa đơn đỏ tải từ cổng thuế về. Mỗi tờ lưu đúng 1 lần, tải lại 100 lần cũng không nhân đôi.",
 ex:"HĐ bán 2kg cà phê, ký hiệu 1C25TAA số 0000123, 500.000đ.",
 add:"worker đêm tải HĐ mới từ cổng thuế",upd:"cổng thuế đổi trạng thái xử lý HĐ",del:"hầu như không xóa (giữ để đối chiếu)"},
invoice_line:{fey:"Các dòng hàng IN TRÊN tờ hóa đơn. 1 hóa đơn có nhiều dòng.",
 ex:"Dòng: 'Cà phê hạt — 2 kg × 250.000'.",
 add:"khi lưu HĐ có nhiều dòng hàng",upd:"hiếm",del:"khi xóa HĐ cha"},
sync_run:{fey:"Cuốn nhật ký: 'lúc 2h sáng máy tự tải 37 hóa đơn, OK'. Để biết lần nào lỗi.",
 ex:"02:00 25/06 — tải 37 HĐ — Succeeded.",
 add:"mỗi lần đồng bộ chạy",upd:"khi lần chạy kết thúc (ghi giờ + kết quả)",del:"dọn log cũ (tùy chọn)"},
/* gl */
account:{fey:"Danh sách các 'ngăn kéo' bỏ tiền: 111=tiền mặt, 131=khách nợ mình… Chỉ ngăn nhỏ nhất (lá) mới bỏ tiền được, ngăn to chỉ để gộp.",
 ex:"111 Tiền mặt › 1111 Tiền VND (lá) · 6428 Chi phí khác.",
 add:"thêm tài khoản con vào hệ thống TK",upd:"đổi tên; đổi 'được ghi sổ' chỉ khi TK chưa có bút toán",del:"chỉ khi TK không có con và không có bút toán nào"},
fiscal_period:{fey:"Cuốn lịch theo tháng/năm. Tháng nào 'đã khóa' thì không ai sửa số liệu tháng đó được nữa.",
 ex:"Tháng 06/2026 — Open.",
 add:"sang kỳ kế toán mới",upd:"khóa kỳ (Open→Closed) hoặc mở lại",del:"hiếm"},
opening_balance:{fey:"Số tiền có sẵn trong mỗi ngăn kéo lúc bắt đầu dùng phần mềm (số dư đầu kỳ).",
 ex:"TK 111 đầu năm: Dư Nợ 50.000.000.",
 add:"khai số dư đầu kỳ; hoặc tự gộp từ tab chi tiết",upd:"khai lại = ghi đè",del:"khai lại kỳ → xóa rồi tạo mới"},
voucher:{fey:"1 phiếu/chứng từ = 1 lần ghi sổ (thu, chi, bán…). Mỗi phiếu phải CÂN: tiền ra ngăn này = tiền vào ngăn kia.",
 ex:"Phiếu chi PC0001 ngày 25/06 — chi 500k mua văn phòng phẩm.",
 add:"lập phiếu thu/chi/bán/mua… hoặc tự sinh từ hóa đơn",upd:"sửa phiếu khi kỳ chưa khóa (thường xóa bút toán cũ tạo lại)",del:"xóa mềm → vào thùng rác (khôi phục được)"},
journal_line:{fey:"1 dòng 'lấy ra/bỏ vào' 1 ngăn kéo. Tổng tiền lấy ra phải bằng tổng tiền bỏ vào — luật bất di bất dịch.",
 ex:"Nợ 6428: 500.000  /  Có 111: 500.000.",
 add:"tự sinh khi lưu/ghi sổ 1 phiếu",upd:"không sửa trực tiếp — sửa phiếu thì xóa hết & tạo lại",del:"khi phiếu cha bị sửa/xóa"},
invoice_payment:{fey:"Ghi chú 'phiếu thu này trả cho hóa đơn nào'. Khách nợ 3 HĐ, trả 1 cục, mình đánh dấu trả HĐ nào.",
 ex:"Phiếu thu PT0005 trả 300k cho HĐ bán #123.",
 add:"khi khớp (đối trừ) thu/chi với hóa đơn còn nợ",upd:"hiếm",del:"khi hủy đối trừ hoặc xóa phiếu"},
transfer_account_pair:{fey:"Danh sách 'cuối tháng dồn tiền từ ngăn A sang ngăn B' (dồn doanh thu, chi phí về lãi/lỗ).",
 ex:"Cuối kỳ: 5111 → 911 (kết chuyển doanh thu).",
 add:"khai 1 cặp kết chuyển",upd:"đổi TK / thứ tự",del:"bỏ cặp không dùng"},
posting_rule:{fey:"Khung quy tắc 'phiếu loại này tự ghi vào ngăn nào'. Thực ra quy tắc nằm trong file cài sẵn nên bảng này gần như trống.",
 ex:"(để trống — đọc từ file misa-account-default.json).",
 add:"hiếm dùng",upd:"—",del:"—"},
default_account:{fey:"Sổ tay ghi nhớ 'mặc định: tiền mặt=111, khách nợ=131', để khỏi gõ lại mỗi lần.",
 ex:"'Tiền mặt'→111 · 'Phải thu KH'→131.",
 add:"seed mặc định khi tạo công ty",upd:"đổi TK ngầm định cho 1 nghiệp vụ",del:"hiếm"},
/* master */
partner:{fey:"Sổ danh bạ: khách hàng, nhà cung cấp, nhân viên. Lưu tên, MST, nợ bao nhiêu, được nợ mấy ngày.",
 ex:"KH00001 — Cửa hàng Minh Tâm, nợ tối đa 20tr, hạn 30 ngày.",
 add:"thêm khách / NCC / nhân viên mới",upd:"cập nhật địa chỉ, hạn mức, TK công nợ",del:"xóa nếu chưa phát sinh (thường tắt thay vì xóa)"},
partner_bank_account:{fey:"Các số TK ngân hàng của 1 người trong danh bạ (1 người có thể nhiều TK).",
 ex:"KH Minh Tâm — VCB 0123456789 CN Q1.",
 add:"thêm số TK cho 1 đối tượng",upd:"sửa số TK / ngân hàng",del:"bỏ TK cũ"},
item:{fey:"Danh mục hàng hóa/dịch vụ bạn mua bán. Đánh dấu 'là dịch vụ' (không kho) hay 'hàng hóa' (phải đếm tồn).",
 ex:"VT001 — Cà phê hạt, ĐVT kg, là hàng hóa (có kho).",
 add:"thêm mặt hàng / dịch vụ",upd:"đổi TK kho/giá vốn, thuế suất",del:"xóa nếu chưa dùng"},
cost_item:{fey:"Cách dán nhãn cho từng khoản chi cho dễ xem: tiền điện, tiền thuê, lương…",
 ex:"CP01 — Chi phí điện nước.",
 add:"thêm khoản mục chi phí",upd:"đổi tên / khoản cha",del:"xóa nếu chưa gắn vào đâu"},
bank_account:{fey:"Các tài khoản ngân hàng CỦA CHÍNH công ty (tiền gửi của mình ở đâu).",
 ex:"Công ty: VCB 0011000123 — sổ cái 112.",
 add:"mở thêm TK ngân hàng",upd:"đổi chi nhánh / chủ TK",del:"đóng TK → tắt IsActive"},
unit:{fey:"Danh sách đơn vị tính: cái, kg, thùng, lít…",ex:"kg · cái · thùng.",
 add:"thêm ĐVT mới",upd:"đổi tên",del:"xóa nếu chưa dùng"},
item_group:{fey:"Cách gom hàng hóa thành nhóm cho dễ tìm.",ex:"Nhóm 'Đồ uống' › con 'Cà phê'.",
 add:"thêm nhóm VTHH",upd:"đổi tên / nhóm cha",del:"xóa nếu trống"},
partner_group:{fey:"Cách gom khách/NCC thành nhóm.",ex:"Nhóm 'Khách VIP'.",
 add:"thêm nhóm đối tượng",upd:"đổi tên",del:"xóa nếu trống"},
tool_type:{fey:"Phân loại công cụ dụng cụ.",ex:"Loại 'Bàn ghế văn phòng'.",
 add:"thêm loại CCDC",upd:"đổi tên",del:"xóa nếu chưa dùng"},
fixed_asset_type:{fey:"Phân loại tài sản lớn + ngăn kéo ghi sổ mặc định cho loại đó.",
 ex:"Loại 'Phương tiện vận tải' — NG 211, KH 2141.",
 add:"thêm loại tài sản",upd:"đổi TK mặc định",del:"xóa nếu chưa dùng"},
project_type:{fey:"Phân loại công trình (cho công ty xây dựng).",ex:"Loại 'Công trình dân dụng'.",
 add:"thêm loại công trình",upd:"đổi tên",del:"xóa nếu chưa dùng"},
bank:{fey:"Danh sách tên ngân hàng để chọn cho nhanh.",ex:"VCB — Vietcombank.",
 add:"thêm ngân hàng",upd:"đổi tên",del:"xóa nếu chưa dùng"},
payment_term:{fey:"Điều khoản nợ: 'được nợ 30 ngày, trả sớm 10 ngày giảm 2%'.",
 ex:"'NET 30' — nợ 30 ngày, trả ≤10 ngày giảm 2%.",
 add:"thêm điều khoản TT",upd:"đổi số ngày / chiết khấu",del:"xóa nếu chưa dùng"},
statistical_code:{fey:"Mã tự đặt để thống kê theo ý mình (vd theo vùng miền).",ex:"TK-MB — Miền Bắc.",
 add:"thêm mã thống kê",upd:"đổi tên",del:"xóa nếu chưa dùng"},
voucher_kind:{fey:"Phân loại nhỏ các phiếu + gợi ý ngăn Nợ/Có, để lọc nhanh 'lý do thu/chi'.",
 ex:"'Thu tiền bán hàng' — Nợ 111 / Có 511.",
 add:"thêm loại chứng từ",upd:"đổi TK gợi ý",del:"xóa nếu chưa dùng"},
department:{fey:"Danh sách phòng ban để chia lương theo bộ phận.",ex:"Phòng Kinh doanh.",
 add:"thêm phòng ban",upd:"đổi tên",del:"xóa nếu trống"},
employee:{fey:"Hồ sơ nhân viên để làm lương: tên, lương cơ bản, mấy người phụ thuộc.",
 ex:"NV001 — Trần Văn A, lương CB 8tr, 2 người phụ thuộc.",
 add:"thêm nhân viên",upd:"tăng lương / đổi phòng",del:"nghỉ việc → tắt (xóa nếu chưa có lương)"},
contract:{fey:"Sổ ghi các hợp đồng mua/bán đã ký, để theo dõi từng hợp đồng lời/lỗ.",
 ex:"HĐ 05/2026 bán cho KH X, giá trị 100tr.",
 add:"ký hợp đồng mới",upd:"đổi giá trị / đóng HĐ",del:"hủy HĐ nhập nhầm"},
/* cash */
cash_flow_item:{fey:"Dán nhãn dòng tiền 'thu từ bán hàng', 'chi trả lương'… để vẽ biểu đồ tiền vào/ra.",
 ex:"'Thu bán hàng' (Thu) / 'Chi lương' (Chi).",
 add:"thêm mục thu/chi",upd:"đổi tên / chiều",del:"xóa nếu chưa dùng"},
cash_count:{fey:"Biên bản đếm tiền trong két: sổ ghi 5tr, đếm thực 4,9tr → lệch 100k phải xử lý.",
 ex:"Kiểm kê két 25/06: sổ 5tr, thực 4,9tr → thiếu 100k.",
 add:"lập biên bản kiểm kê quỹ",upd:"sửa khi chưa xử lý chênh lệch",del:"hủy biên bản nhầm"},
cash_count_denom:{fey:"Bảng đếm 'có mấy tờ 500k, mấy tờ 200k…' khi kiểm kê két.",
 ex:"10 tờ 200k + 9 tờ 100k.",
 add:"khi nhập mệnh giá lúc kiểm kê",upd:"sửa số lượng tờ",del:"theo biên bản cha"},
cash_count_member:{fey:"Danh sách người tham gia đếm tiền (để ký biên bản).",
 ex:"Thủ quỹ + Kế toán trưởng.",
 add:"khi thêm thành viên hội đồng",upd:"đổi tên/chức danh",del:"theo biên bản cha"},
bank_reconciliation:{fey:"Đối chiếu sổ của mình với sao kê ngân hàng gửi về, xem khớp không.",
 ex:"Đối chiếu VCB tháng 6: sao kê 200tr.",
 add:"lập đối chiếu 1 kỳ",upd:"tick khớp thêm chứng từ",del:"hủy đối chiếu"},
loan_contract:{fey:"Khế ước vay tiền + lịch trả gốc/lãi từng tháng.",
 ex:"Vay ACB 500tr, trả 12 kỳ.",
 add:"ký khế ước vay",upd:"điều chỉnh lịch trả",del:"tất toán / nhập nhầm"},
/* asset */
tool:{fey:"Công cụ dụng cụ (bàn ghế, dụng cụ nhỏ): giá trị chia đều ra nhiều tháng thành chi phí, thay vì tính hết 1 lần.",
 ex:"CC001 — Bộ bàn ghế 12tr, phân bổ 24 tháng = 500k/tháng.",
 add:"ghi tăng 1 CCDC",upd:"sửa khi chưa phân bổ kỳ nào",del:"ghi giảm / xóa nếu chưa phân bổ"},
tool_allocation:{fey:"Nhật ký 'tháng này đã phân bổ công cụ X rồi', để khỏi phân bổ trùng.",
 ex:"06/2026 — phân bổ CC001 500k.",
 add:"khi chạy phân bổ kỳ",upd:"không (chống trùng)",del:"khi hủy phân bổ kỳ đó"},
fixed_asset:{fey:"Tài sản lớn (ô tô, máy): mỗi tháng 'hao mòn' 1 ít (khấu hao). Còn lại = giá mua − hao mòn đã tính.",
 ex:"TS001 — Ô tô 600tr, khấu hao 60 tháng = 10tr/tháng.",
 add:"ghi tăng 1 TSCĐ",upd:"sửa khi chưa khấu hao kỳ nào",del:"thanh lý / ghi giảm"},
fixed_asset_dep:{fey:"Nhật ký 'tháng này đã trích khấu hao tài sản X rồi', để khỏi trích trùng.",
 ex:"06/2026 — khấu hao TS001 10tr.",
 add:"khi chạy khấu hao kỳ",upd:"không (chống trùng)",del:"khi hủy khấu hao kỳ đó"},
/* payroll */
payroll_sheet:{fey:"Bảng lương 1 tháng cho cả công ty. Bấm nút là tự tính bảo hiểm, thuế TNCN và ghi sổ.",
 ex:"Bảng lương 06/2026 — ghi vào chi phí 642.",
 add:"lập bảng lương tháng",upd:"sửa khi chưa ghi sổ",del:"xóa bảng nháp"},
payroll_line:{fey:"1 dòng = 1 nhân viên trong bảng lương: lương, ngày công, phụ cấp. Máy tự tính thực lĩnh.",
 ex:"Trần Văn A: 26/26 công, gross 8tr, phụ cấp 500k.",
 add:"thêm dòng / nhập từ danh mục NV",upd:"sửa công / phụ cấp",del:"bỏ NV khỏi bảng"},
/* tax */
tax_declaration:{fey:"Tờ khai thuế GTGT đã nộp 1 kỳ. Chỉ lưu con số 'còn được khấu trừ chuyển kỳ sau', phần còn lại máy tự tính từ sổ.",
 ex:"01/GTGT Q2/2026 — còn khấu trừ chuyển kỳ sau 3tr.",
 add:"chốt tờ khai 1 kỳ",upd:"lưu lại = ghi đè kỳ đó",del:"hiếm"},
/* stock */
warehouse:{fey:"Danh sách các kho hàng.",ex:"Kho 'KCN' — kho chính.",
 add:"thêm kho",upd:"đổi tên",del:"xóa nếu trống"},
stock_movement:{fey:"Mỗi lần hàng vào hoặc ra kho ghi 1 dòng. Cộng nhập − xuất = tồn kho (không cần bảng tồn riêng).",
 ex:"Nhập 100 thùng @50k = 5tr (Nợ 156 / Có 331).",
 add:"khi lưu phiếu nhập/xuất, chuyển kho, hoặc tồn đầu kỳ",upd:"không sửa trực tiếp",del:"khi phiếu cha bị sửa/xóa"},
stock_count:{fey:"Biên bản kiểm kê kho: sổ ghi 100, đếm thực 98 → thiếu 2 phải xử lý.",
 ex:"Kiểm kê kho 30/06: thiếu 2 thùng.",
 add:"lập biên bản kiểm kê kho",upd:"sửa khi chưa xử lý",del:"hủy biên bản"},
stock_count_line:{fey:"1 dòng đếm 1 mặt hàng: theo sổ bao nhiêu, đếm thực bao nhiêu, còn tốt/hỏng/mất.",
 ex:"Cà phê: sổ 100, thực 98, mất 2.",
 add:"khi nhập dòng kiểm kê",upd:"sửa số đếm thực",del:"theo biên bản cha"},
stock_count_member:{fey:"Người tham gia kiểm kê kho (để ký).",ex:"Thủ kho + Kế toán trưởng.",
 add:"khi thêm thành viên",upd:"đổi tên",del:"theo biên bản cha"},
/* costing */
cost_object:{fey:"'Cái nồi' gom chi phí: 1 sản phẩm, 1 công trình, 1 đơn hàng. Đổ hết chi phí làm ra nó vào đây.",
 ex:"'Công trình Nhà A' — gom mọi chi phí xây nhà A.",
 add:"mở 1 đối tượng tập hợp chi phí",upd:"đổi tên / loại",del:"xóa nếu chưa dùng"},
costing_period:{fey:"1 đợt tính giá thành: cuối kỳ gom hết chi phí trong các 'nồi' để ra giá thành bao nhiêu tiền.",
 ex:"Kỳ giá thành Q2/2026 — phương pháp giản đơn.",
 add:"mở kỳ tính giá thành",upd:"'lấy dữ liệu' / tính lại",del:"hủy kỳ"},
costing_period_line:{fey:"1 dòng = 1 sản phẩm/công trình trong đợt: bỏ vào bao nhiêu chi phí → ra giá thành 1 đơn vị.",
 ex:"Nhà A: chi phí 800tr → giá thành/đơn vị.",
 add:"khi 'lấy dữ liệu' kéo đối tượng có chi phí",upd:"nhập dở dang & tính",del:"theo kỳ cha"},
/* sales */
price_policy:{fey:"Bảng giá bán: hàng này bán bao nhiêu, cho nhóm khách nào, hiệu lực từ ngày nào.",
 ex:"'Bảng giá 2026' cho nhóm Khách VIP.",
 add:"lập bảng giá",upd:"sửa hiệu lực / giá",del:"bỏ bảng giá"},
price_policy_line:{fey:"1 dòng giá: mặt hàng X giá Y. Khi bán tự điền giá này.",
 ex:"Cà phê — 260.000/kg.",
 add:"thêm dòng giá",upd:"đổi đơn giá",del:"theo bảng giá cha"},
deferred_revenue:{fey:"Tiền khách trả trước cho dịch vụ dài hạn (thuê 1 năm). Chưa tính hết doanh thu mà chia đều từng tháng.",
 ex:"Khách trả trước 12tr thuê 12 tháng → 1tr/tháng.",
 add:"ghi nhận tiền nhận trước",upd:"sửa khi chưa phân bổ",del:"xóa nếu chưa phân bổ kỳ nào"},
deferred_revenue_alloc:{fey:"Nhật ký 'tháng này đã ghi nhận 1 phần doanh thu trả trước', tránh ghi trùng.",
 ex:"06/2026 — ghi 1tr doanh thu.",
 add:"khi phân bổ kỳ",upd:"không (chống trùng)",del:"khi hủy phân bổ"},
sales_order:{fey:"Đơn khách đặt hàng (chưa giao, chưa ghi sổ). Giao thật mới bấm 'lập chứng từ' để ghi doanh thu.",
 ex:"Đơn ĐH 07/2026 — KH X, 50 thùng.",
 add:"khi khách đặt hàng",upd:"sửa số lượng (khi chưa lập CT)",del:"hủy đơn"},
sales_order_line:{fey:"Các dòng hàng trong đơn đặt hàng.",ex:"Cà phê — 50 thùng @ 260k.",
 add:"khi nhập dòng đơn hàng",upd:"đổi SL / giá",del:"theo đơn cha"},
quotation:{fey:"Báo giá gửi khách (chưa chốt gì). Khách đồng ý thì chuyển thành đơn hàng.",
 ex:"Báo giá BG10 gửi KH X.",
 add:"tạo báo giá",upd:"sửa giá chào",del:"hủy báo giá"},
quotation_line:{fey:"Các dòng hàng trong báo giá.",ex:"Cà phê — 50 thùng @ 270k.",
 add:"khi nhập dòng báo giá",upd:"đổi SL / giá",del:"theo báo giá cha"},
/* opening */
opening_party:{fey:"Lúc mới dùng phần mềm: ghi 'khách A đang nợ mình 5tr, mình nợ NCC B 3tr' — nợ cũ chi tiết từng người.",
 ex:"Đầu kỳ: KH Minh Tâm nợ mình 5tr (131).",
 add:"khai công nợ đầu kỳ theo đối tượng",upd:"lưu lại = ghi đè",del:"khai lại → xóa & thêm lại"},
opening_stock:{fey:"Lúc mới dùng phần mềm: ghi 'kho đang có sẵn 100 thùng trị giá X' — tồn kho có sẵn.",
 ex:"Đầu kỳ: 100 thùng cà phê @50k = 5tr.",
 add:"khai tồn đầu kỳ (tự sinh phiếu nhập SDDK)",upd:"lưu lại = ghi đè",del:"khai lại → xóa & thêm lại"},
opening_bank_balance:{fey:"Lúc mới dùng phần mềm: ghi 'TK Vietcombank đang có sẵn 200tr' — số dư ngân hàng có sẵn.",
 ex:"Đầu kỳ: VCB (112) dư 200tr.",
 add:"khai số dư NH đầu kỳ",upd:"lưu lại = ghi đè",del:"khai lại → xóa & thêm lại"},
/* setup */
company_settings:{fey:"Bảng tùy chỉnh cho từng công ty: năm tài chính bắt đầu tháng mấy, làm tròn mấy số lẻ…",
 ex:"Năm TC bắt đầu tháng 1, tiền 0 số lẻ.",
 add:"tạo khi lưu tùy chọn lần đầu",upd:"đổi tùy chọn",del:"không có bản ghi = dùng mặc định"},
company_signature:{fey:"Tên những người ký (giám đốc, KT trưởng) để in lên cuối chứng từ.",
 ex:"Giám đốc — Nguyễn Văn B.",
 add:"thêm người ký",upd:"đổi tên / chức danh",del:"bỏ người ký"},
user:{fey:"Tài khoản đăng nhập phần mềm. Mật khẩu lưu dạng băm (không ai đọc được), phân quyền theo vai trò.",
 ex:"admin@lixin.vn — vai trò Admin.",
 add:"tạo tài khoản đăng nhập",upd:"đổi mật khẩu / vai trò",del:"khóa (IsActive=false) thay vì xóa"},
audit_log:{fey:"Camera an ninh: ghi lại ai làm gì lúc nào (đăng nhập, tạo phiếu, sửa, xóa).",
 ex:"08:15 — admin POST phiếu PC0001.",
 add:"tự ghi mỗi thao tác",upd:"không bao giờ sửa",del:"không xóa (chỉ dọn định kỳ)"},
staff:{fey:"Nhân viên của CHÍNH văn phòng dịch vụ kế toán (khác nhân viên của công ty khách).",
 ex:"Kế toán viên Lan, phụ trách 5 công ty.",
 add:"thêm nhân sự văn phòng",upd:"đổi thông tin",del:"nghỉ việc"},
company_assignment:{fey:"Phân công 'bạn kế toán nào lo công ty nào'.",
 ex:"Lan ↔ Công ty Cà Phê Sạch.",
 add:"phân công phụ trách",upd:"—",del:"đổi người phụ trách"},
};
